/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as PowensCallbackRouteImport } from './routes/powens/callback'
import { Route as AppProfilesRouteImport } from './routes/_app/profiles'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts.index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts.$accountId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PowensCallbackRoute = PowensCallbackRouteImport.update({
  id: '/powens/callback',
  path: '/powens/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connections': typeof AppConnectionsRoute
  '/profiles': typeof AppProfilesRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/connections': typeof AppConnectionsRoute
  '/profiles': typeof AppProfilesRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts': typeof AppAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/profiles': typeof AppProfilesRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/profiles'
    | '/powens/callback'
    | '/sign-in/$'
    | '/accounts/$accountId'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/profiles'
    | '/powens/callback'
    | '/sign-in/$'
    | '/'
    | '/accounts/$accountId'
    | '/accounts'
  id:
    | '__root__'
    | '/_app'
    | '/_app/connections'
    | '/_app/profiles'
    | '/powens/callback'
    | '/sign-in/$'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PowensCallbackRoute: typeof PowensCallbackRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powens/callback': {
      id: '/powens/callback'
      path: '/powens/callback'
      fullPath: '/powens/callback'
      preLoaderRoute: typeof PowensCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profiles': {
      id: '/_app/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PowensCallbackRoute: PowensCallbackRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
