/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SettingsRouteImport } from './routes/_settings'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as PowensCallbackRouteImport } from './routes/powens/callback'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppProfilesRouteImport } from './routes/_app/profiles'
import { Route as SettingsSettingsIndexRouteImport } from './routes/_settings/settings.index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts.index'
import { Route as SettingsSettingsSecurityRouteImport } from './routes/_settings/settings.security'
import { Route as SettingsSettingsProfileRouteImport } from './routes/_settings/settings.profile'
import { Route as SettingsSettingsMembersRouteImport } from './routes/_settings/settings.members'
import { Route as SettingsSettingsEncryptionRouteImport } from './routes/_settings/settings.encryption'
import { Route as SettingsSettingsConnectionsRouteImport } from './routes/_settings/settings.connections'
import { Route as SettingsSettingsCategoriesRouteImport } from './routes/_settings/settings.categories'
import { Route as SettingsSettingsBillingRouteImport } from './routes/_settings/settings.billing'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts.$accountId'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PowensCallbackRoute = PowensCallbackRouteImport.update({
  id: '/powens/callback',
  path: '/powens/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const SettingsSettingsIndexRoute = SettingsSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SettingsRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsSettingsSecurityRoute =
  SettingsSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsProfileRoute = SettingsSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsMembersRoute = SettingsSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsEncryptionRoute =
  SettingsSettingsEncryptionRouteImport.update({
    id: '/settings/encryption',
    path: '/settings/encryption',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsConnectionsRoute =
  SettingsSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsCategoriesRoute =
  SettingsSettingsCategoriesRouteImport.update({
    id: '/settings/categories',
    path: '/settings/categories',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsBillingRoute = SettingsSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/checkout': typeof CheckoutRoute
  '/profiles': typeof AppProfilesRoute
  '/transactions': typeof AppTransactionsRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/billing': typeof SettingsSettingsBillingRoute
  '/settings/categories': typeof SettingsSettingsCategoriesRoute
  '/settings/connections': typeof SettingsSettingsConnectionsRoute
  '/settings/encryption': typeof SettingsSettingsEncryptionRoute
  '/settings/members': typeof SettingsSettingsMembersRoute
  '/settings/profile': typeof SettingsSettingsProfileRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/checkout': typeof CheckoutRoute
  '/profiles': typeof AppProfilesRoute
  '/transactions': typeof AppTransactionsRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/billing': typeof SettingsSettingsBillingRoute
  '/settings/categories': typeof SettingsSettingsCategoriesRoute
  '/settings/connections': typeof SettingsSettingsConnectionsRoute
  '/settings/encryption': typeof SettingsSettingsEncryptionRoute
  '/settings/members': typeof SettingsSettingsMembersRoute
  '/settings/profile': typeof SettingsSettingsProfileRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/settings': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_settings': typeof SettingsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/_app/profiles': typeof AppProfilesRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_settings/settings/billing': typeof SettingsSettingsBillingRoute
  '/_settings/settings/categories': typeof SettingsSettingsCategoriesRoute
  '/_settings/settings/connections': typeof SettingsSettingsConnectionsRoute
  '/_settings/settings/encryption': typeof SettingsSettingsEncryptionRoute
  '/_settings/settings/members': typeof SettingsSettingsMembersRoute
  '/_settings/settings/profile': typeof SettingsSettingsProfileRoute
  '/_settings/settings/security': typeof SettingsSettingsSecurityRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_settings/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/profiles'
    | '/transactions'
    | '/powens/callback'
    | '/sign-in/$'
    | '/accounts/$accountId'
    | '/settings/billing'
    | '/settings/categories'
    | '/settings/connections'
    | '/settings/encryption'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/security'
    | '/accounts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/profiles'
    | '/transactions'
    | '/powens/callback'
    | '/sign-in/$'
    | '/accounts/$accountId'
    | '/settings/billing'
    | '/settings/categories'
    | '/settings/connections'
    | '/settings/encryption'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/security'
    | '/accounts'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_settings'
    | '/checkout'
    | '/_app/profiles'
    | '/_app/transactions'
    | '/powens/callback'
    | '/sign-in/$'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_settings/settings/billing'
    | '/_settings/settings/categories'
    | '/_settings/settings/connections'
    | '/_settings/settings/encryption'
    | '/_settings/settings/members'
    | '/_settings/settings/profile'
    | '/_settings/settings/security'
    | '/_app/accounts/'
    | '/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  PowensCallbackRoute: typeof PowensCallbackRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powens/callback': {
      id: '/powens/callback'
      path: '/powens/callback'
      fullPath: '/powens/callback'
      preLoaderRoute: typeof PowensCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles': {
      id: '/_app/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_settings/settings/': {
      id: '/_settings/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_settings/settings/security': {
      id: '/_settings/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/profile': {
      id: '/_settings/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsSettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/members': {
      id: '/_settings/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsSettingsMembersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/encryption': {
      id: '/_settings/settings/encryption'
      path: '/settings/encryption'
      fullPath: '/settings/encryption'
      preLoaderRoute: typeof SettingsSettingsEncryptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/connections': {
      id: '/_settings/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsSettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/categories': {
      id: '/_settings/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsSettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/billing': {
      id: '/_settings/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsSettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfilesRoute: typeof AppProfilesRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfilesRoute: AppProfilesRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsRouteChildren {
  SettingsSettingsBillingRoute: typeof SettingsSettingsBillingRoute
  SettingsSettingsCategoriesRoute: typeof SettingsSettingsCategoriesRoute
  SettingsSettingsConnectionsRoute: typeof SettingsSettingsConnectionsRoute
  SettingsSettingsEncryptionRoute: typeof SettingsSettingsEncryptionRoute
  SettingsSettingsMembersRoute: typeof SettingsSettingsMembersRoute
  SettingsSettingsProfileRoute: typeof SettingsSettingsProfileRoute
  SettingsSettingsSecurityRoute: typeof SettingsSettingsSecurityRoute
  SettingsSettingsIndexRoute: typeof SettingsSettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsBillingRoute: SettingsSettingsBillingRoute,
  SettingsSettingsCategoriesRoute: SettingsSettingsCategoriesRoute,
  SettingsSettingsConnectionsRoute: SettingsSettingsConnectionsRoute,
  SettingsSettingsEncryptionRoute: SettingsSettingsEncryptionRoute,
  SettingsSettingsMembersRoute: SettingsSettingsMembersRoute,
  SettingsSettingsProfileRoute: SettingsSettingsProfileRoute,
  SettingsSettingsSecurityRoute: SettingsSettingsSecurityRoute,
  SettingsSettingsIndexRoute: SettingsSettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  PowensCallbackRoute: PowensCallbackRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
